### ISSUE TITLE
Handle C++ exceptions properly

### ISSUE THREAD

**Issue by alexhroom** [RascalSoftware/RasCAL-2#26]
Currently workarounds are used (e.g. see the `EditControls` command) to handle crashes while C++ is handling Python code. These exceptions should be handled properly and the workarounds removed.

**Comment by StephenNneji** [comment]
I had a quick look at this issue, and it should be possible to catch an exception in a command by default, what we cannot do is propagate the exception, as exceptions in slots have undefined behaviour in QT (https://doc.qt.io/qtforpython-6/overviews/exceptionsafety.html#signals-and-slots), but I am adding a function to log the exceptions in #37 

So It might be better to leave [EditControls](https://github.com/RascalSoftware/RasCAL-2/blob/23cfcbdf5fad02a4ff6c5b4c6077aeb2da84f52c/rascal2/core/commands.py#L19) as it is because we will have to store and  retrieve the exception from the command as it cannot be propagated

**Comment by alexhroom** [comment]
closing, then as exceptions are now properly logged but cannot be properly solved
