### ISSUE TITLE
AdaptiveDoubleSpinBox has erratic behaviour

### ISSUE THREAD

**Issue by StephenNneji** [RascalSoftware/RasCAL-2#32]
When stepping down the spinbox switches to scientific format in a erratic way, see attached clip

Transitions should be smoother, in the example below I would expect it to go from 0.1 to 0 and back to 0.1 instead of 1e-17

https://github.com/user-attachments/assets/a46eaccf-e5ea-43e8-9373-5422b5379aad

**Comment by alexhroom** [comment]
the reason it's adaptive is because it adapts the number of decimal places to whatever the user input is: e.g. if `QDoubleSpinBox.decimals` is firmly set to 1, you're not even allowed to *type* 0.0001 - it'll just stop you from typing more than 1 decimal place worth of digits. i'll see if i can make it only do that for typing, and not for clicking up and down, but i don't know whether it's that flexible or whether both options direct themselves through the same method
